[versions]
# Plugins
kotlin = "2.0.21"
plugin-publish = "2.0.0"
sonarqube = "7.2.2.6593"

# Android
android-gradle-plugin = "9.0.1"

# Testing
junit5 = "6.0.3"
mockk = "1.14.9"
assertk = "0.28.1"

# Libraries
kotlinpoet = "2.2.0"

[libraries]
# Gradle plugin dependencies
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Code generation
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# Testing
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit5" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
